/**
 * Especificaciones de carreras UNIMET para el test ICO: base para preguntas
 * adaptadas (reactivo + contexto de carrera) y para el LLM de orientación vocacional.
 * Interest code = RIASEC. Verbos y áreas sirven para redactar preguntas contextualizadas.
 */
module.exports = {
  CARRERAS_UNIMET: [
    {
      name: 'Ingeniería Civil',
      interestCode: 'RIC',
      faculty: 'Ingeniería',
      area: 'Infraestructura, Obras hidráulicas, Vías',
      verbos: ['Diseñar', 'Calcular', 'Inspeccionar', 'Construir', 'Gestionar', 'Analizar', 'Modelar'],
      areasTrabajo: ['Infraestructura habitacional y comercial', 'Obras hidráulicas y saneamiento', 'Vías y transporte', 'Geotecnia y suelos'],
    },
    {
      name: 'Ingeniería Mecánica',
      interestCode: 'RIC',
      faculty: 'Ingeniería',
      area: 'Plantas industriales, Energía, Manufactura',
      verbos: ['Diseñar', 'Fabricar', 'Analizar', 'Inspeccionar', 'Mantener', 'Operar', 'Modelar'],
      areasTrabajo: ['Plantas industriales', 'Energía', 'Sistemas de manufactura', 'Mecánica de transporte', 'Instrumentación y automatización'],
    },
    {
      name: 'Ingeniería de Producción',
      interestCode: 'CIR',
      faculty: 'Ingeniería',
      area: 'Operaciones, Logística, Calidad',
      verbos: ['Organizar', 'Planificar', 'Mejorar', 'Controlar', 'Optimizar', 'Generar', 'Resolver', 'Diseñar', 'Investigar'],
      areasTrabajo: ['Procesos de producción', 'Área de operaciones', 'Plantas industriales', 'Logística y distribución', 'Gestión de la calidad'],
    },
    {
      name: 'Ingeniería Química',
      interestCode: 'RIC',
      faculty: 'Ingeniería',
      area: 'Procesos, Industria química, I+D',
      verbos: ['Transformar', 'Resolver', 'Diseñar', 'Simular', 'Operar', 'Optimizar', 'Evaluar', 'Planificar', 'Analizar'],
      areasTrabajo: ['Industria de procesos', 'Recursos energéticos', 'Alimentos', 'Recursos naturales', 'Control ambiental', 'Investigación y desarrollo'],
    },
    {
      name: 'Ingeniería de Sistemas',
      interestCode: 'ICR',
      faculty: 'Ingeniería',
      area: 'Sistemas de información, Software, Consultoría',
      verbos: ['Estudiar', 'Resolver', 'Crear', 'Diseñar', 'Desarrollar', 'Optimizar', 'Gestionar', 'Consultar'],
      areasTrabajo: ['Sistemas de información', 'Investigación de operaciones', 'Consultoría de empresas', 'Tecnologías emergentes', 'Gestión de proyectos TIC'],
    },
    {
      name: 'Ingeniería Eléctrica',
      interestCode: 'RIC',
      faculty: 'Ingeniería',
      area: 'Potencia, Control, Telecomunicaciones',
      verbos: ['Diseñar', 'Construir', 'Analizar', 'Modelar', 'Instalar', 'Operar', 'Mantener', 'Programar', 'Evaluar'],
      areasTrabajo: ['Sistemas de potencia', 'Control y automatización industrial', 'Telecomunicaciones', 'Energías renovables', 'Electrónica'],
    },
    {
      name: 'Ciencias Administrativas',
      interestCode: 'EC',
      faculty: 'Ciencias Administrativas',
      area: 'Gestión, Finanzas, Gerencia',
      verbos: ['Desarrollar', 'Fortalecer', 'Comprender', 'Abordar', 'Lograr', 'Aplicar', 'Tomar decisiones', 'Generar', 'Promover', 'Solucionar', 'Manejar'],
      areasTrabajo: ['Gestión de recursos humanos', 'Gestión de mercadotecnia', 'Gestión logística y producción', 'Gerencia', 'Banca y finanzas'],
    },
    {
      name: 'Economía Empresarial',
      interestCode: 'ICE',
      faculty: 'Ciencias Administrativas',
      area: 'Análisis económico, Banca, Desarrollo',
      verbos: ['Aplicar', 'Resolver', 'Generar', 'Manejar', 'Comprender', 'Diseñar', 'Contribuir'],
      areasTrabajo: ['Planificación estratégica y mercadeo', 'Comercio internacional', 'Análisis económico', 'Gestión de ONGs', 'Gestión empresarial'],
    },
    {
      name: 'Contaduría Pública',
      interestCode: 'CEI',
      faculty: 'Ciencias Administrativas',
      area: 'Auditoría, Tributos, Finanzas',
      verbos: ['Preparar', 'Revisar', 'Auditar', 'Analizar', 'Interpretar', 'Evaluar', 'Optimizar', 'Dirigir'],
      areasTrabajo: ['Auditoría independiente', 'Planificación financiera', 'Consultoría', 'Gerencia de impuestos', 'Emprendimiento'],
    },
    {
      name: 'Psicología',
      interestCode: 'SI',
      faculty: 'Ciencias',
      area: 'Clínica, Organizacional, Educativa, Social',
      verbos: ['Comprender', 'Construir', 'Transformar', 'Diseñar', 'Aplicar', 'Observar', 'Analizar', 'Identificar', 'Diagnosticar', 'Intervenir', 'Evaluar', 'Investigar', 'Validar'],
      areasTrabajo: ['Clínica', 'Organizacional', 'Educativa', 'Social y comunitaria', 'Investigación', 'Salud pública'],
    },
    {
      name: 'Matemáticas Industriales',
      interestCode: 'IC',
      faculty: 'Ciencias',
      area: 'Data Science, Finanzas, IA, Investigación',
      verbos: ['Analizar', 'Modelar', 'Liderar', 'Innovar', 'Programar', 'Interpretar', 'Describir', 'Crear', 'Dominar', 'Gestionar'],
      areasTrabajo: ['Ciencia de datos', 'Sector financiero', 'Tecnología de vanguardia', 'Inteligencia artificial', 'Investigación y academia'],
    },
    {
      name: 'Educación',
      interestCode: 'SAE',
      faculty: 'Humanidades',
      area: 'Docencia, Gerencia educativa, Investigación',
      verbos: ['Ejercer', 'Capacitar', 'Promover', 'Administrar', 'Atender', 'Resolver', 'Planificar', 'Evaluar', 'Investigar'],
      areasTrabajo: ['Docencia', 'Gerencia educativa', 'Gestión de programas sociales', 'Promoción comunitaria', 'Diseño curricular'],
    },
    {
      name: 'Idiomas Modernos',
      interestCode: 'AIS',
      faculty: 'Humanidades',
      area: 'Traducción, Interpretación, Docencia',
      verbos: ['Comunicar', 'Traducir', 'Interpretar', 'Subtitular', 'Diseñar', 'Investigar', 'Gestionar', 'Negociar', 'Localizar', 'Analizar'],
      areasTrabajo: ['Traducción e interpretación', 'Traducción audiovisual', 'Mundo empresarial', 'Docencia e investigación', 'Consultoría intercultural'],
    },
    {
      name: 'Comunicación Social y Empresarial',
      interestCode: 'EAS',
      faculty: 'Humanidades',
      area: 'Comunicación digital, Marketing, Producción',
      verbos: ['Redefinir', 'Gestionar', 'Aplicar', 'Analizar', 'Producir', 'Diseñar', 'Optimizar', 'Asesorar', 'Manejar'],
      areasTrabajo: ['Liderazgo en comunicación digital', 'Gestión de reputación y crisis', 'Growth marketing', 'Consultoría en transformación digital', 'Producción de contenidos'],
    },
    {
      name: 'Turismo Sostenible',
      interestCode: 'ESC',
      faculty: 'Humanidades',
      area: 'Hospitalidad, Destinos, Emprendimiento turístico',
      verbos: ['Liderar', 'Generar', 'Emprender', 'Trabajar', 'Integrar', 'Preservar', 'Transformar'],
      areasTrabajo: ['Empresas de hospitalidad', 'Gestión de destinos turísticos', 'Agencias y tour operadores', 'Emprendimiento turístico', 'Organismos internacionales y ONGs'],
    },
    {
      name: 'Estudios Liberales',
      interestCode: 'IAS',
      faculty: 'Estudios Jurídicos y Políticos',
      area: 'Análisis internacional, Política, Estrategia',
      verbos: ['Comprender', 'Interpretar', 'Analizar', 'Buscar soluciones', 'Diseñar', 'Liderar', 'Contribuir', 'Armonizar'],
      areasTrabajo: ['Planificación estratégica y mercadeo', 'Comercio internacional', 'Evaluación de escenarios', 'Asesoría institucional', 'Gestión pública'],
    },
    {
      name: 'Derecho',
      interestCode: 'EI',
      faculty: 'Estudios Jurídicos y Políticos',
      area: 'Legal, Consultoría, Negociación',
      verbos: ['Prevenir', 'Resolver', 'Garantizar', 'Regular', 'Negociar', 'Razonar', 'Argumentar', 'Investigar', 'Actuar'],
      areasTrabajo: ['Firma propia', 'Bufetes corporativos', 'Consultoría', 'Organizaciones internacionales'],
    },
    {
      name: 'Estudios Internacionales',
      interestCode: 'IC',
      faculty: 'Estudios Jurídicos y Políticos',
      area: 'Organismos internacionales, Diplomacia, Proyectos',
      verbos: ['Comprender', 'Desempeñarse', 'Liderar', 'Gestionar', 'Enfrentar', 'Analizar', 'Diseñar'],
      areasTrabajo: ['Organismos internacionales', 'Consultoras especializadas', 'Servicio exterior', 'Gestión de proyectos'],
    },
  ],
};
